/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 06-02-2016 08:10:48
 * Name: echo_response.h
 * Description:
 *   This file contains definition of EchoResponse class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE_EXAMPLES_ECHOER__ECHO_RESPONSE_H_
#define _IR_NTNAEEM_GATE_EXAMPLES_ECHOER__ECHO_RESPONSE_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace ir {
namespace ntnaeem {
namespace gate {
namespace examples {
namespace echoer {
  class EchoResponse : public ::naeem::hottentot::runtime::Serializable {
  public:
    EchoResponse() {}
    EchoResponse(const EchoResponse &);
    EchoResponse(EchoResponse *);
    virtual ~EchoResponse() {}
  public:
    inline ::naeem::hottentot::runtime::types::Utf8String GetReply() const {
      return reply_;
    }
    inline void SetReply(::naeem::hottentot::runtime::types::Utf8String reply) {
      reply_ = reply;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::Utf8String reply_;
  };
} // END OF NAMESPACE echoer
} // END OF NAMESPACE examples
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif