/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 06-02-2016 12:36:46
 * Name: transport_service.h
 * Description:
 *   This file contains definition of service interface.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__SERVICE__TRANSPORT_SERVICE_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__SERVICE__TRANSPORT_SERVICE_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/service/hot_context.h>

#include "../accept_report.h"
#include "../transport_message_status.h"
#include "../transport_message.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
namespace service {
  class TransportService {
  public:
     TransportService() {}
     virtual ~TransportService() {}
  public:
    virtual void AcceptSlaveMassages(
      ::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::TransportMessage> &messages, 
      ::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::AcceptReport> &out, 
      ::naeem::hottentot::runtime::service::HotContext &hotContext
    ) = 0;
    virtual void RetrieveSlaveMessages(
      ::naeem::hottentot::runtime::types::UInt32 &slaveId, 
      ::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::TransportMessage> &out, 
      ::naeem::hottentot::runtime::service::HotContext &hotContext
    ) = 0;
    virtual void Ack(
      ::naeem::hottentot::runtime::types::List< ::naeem::hottentot::runtime::types::UInt64> &masterMIds, 
      ::naeem::hottentot::runtime::service::HotContext &hotContext
    ) = 0;
    virtual void GetStatus(
      ::naeem::hottentot::runtime::types::UInt64 &masterMId, 
      ::ir::ntnaeem::gate::transport::TransportMessageStatus &out, 
      ::naeem::hottentot::runtime::service::HotContext &hotContext
    ) = 0;
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif