/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 24-01-2016 03:08:11
 * Name: gate_service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE__PROXY__GATE_SERVICE_PROXY_H_
#define _IR_NTNAEEM_GATE__PROXY__GATE_SERVICE_PROXY_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "../gate_service.h"


namespace ir {
namespace ntnaeem {
namespace gate {
class Status;
class Message;
namespace proxy {
  class GateServiceProxy : public ::ir::ntnaeem::gate::GateService, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    GateServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~GateServiceProxy() {}
  public:
    virtual void EnqueueMessage(::ir::ntnaeem::gate::Message &message, ::naeem::hottentot::runtime::types::UInt32 &);
    virtual void GetMessageStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::ir::ntnaeem::gate::Status &);
    virtual void HasMoreMessage(::naeem::hottentot::runtime::types::Utf8String &label, ::naeem::hottentot::runtime::types::Boolean &);
    virtual void NextMessage(::naeem::hottentot::runtime::types::Utf8String &label, ::naeem::hottentot::runtime::types::Boolean &messageRetrieved, ::ir::ntnaeem::gate::Message &);
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif