/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 03-02-2016 03:40:24
 * Name: gate_service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE__PROXY__GATE_SERVICE_PROXY_H_
#define _IR_NTNAEEM_GATE__PROXY__GATE_SERVICE_PROXY_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "../gate_service.h"


namespace ir {
namespace ntnaeem {
namespace gate {
class MessageStatus;
class Message;
namespace proxy {
  class GateServiceProxy : public ::ir::ntnaeem::gate::GateService, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    GateServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~GateServiceProxy() {}
  public:
    virtual void EnqueueMessage(::ir::ntnaeem::gate::Message &message, ::naeem::hottentot::runtime::types::UInt64 &);
    virtual void GetMessageStatus(::naeem::hottentot::runtime::types::UInt64 &id, ::ir::ntnaeem::gate::MessageStatus &);
    virtual void HasMoreMessage(::naeem::hottentot::runtime::types::Utf8String &label, ::naeem::hottentot::runtime::types::Boolean &);
    virtual void NextMessage(::naeem::hottentot::runtime::types::Utf8String &label, ::ir::ntnaeem::gate::Message &);
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif