/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 01:23:32
 * Name: transport_service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE__PROXY__TRANSPORT_SERVICE_PROXY_H_
#define _IR_NTNAEEM_GATE__PROXY__TRANSPORT_SERVICE_PROXY_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "../transport_service.h"


namespace ir {
namespace ntnaeem {
namespace gate {
class Message;
namespace proxy {
  class TransportServiceProxy : public ::ir::ntnaeem::gate::TransportService, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    TransportServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~TransportServiceProxy() {}
  public:
    virtual void Send(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::Message> &parcels, ::naeem::hottentot::runtime::types::List< ::naeem::hottentot::runtime::types::UInt32> &);
    virtual void Receive(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::Message> &);
    virtual void GetMessageStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::naeem::hottentot::runtime::types::UInt32 &);
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif