all:
	mkdir -p bin
	mkdir -p lib
	mkdir -p lib/proxy
	mkdir -p lib/service
	mkdir -p lib/client
	mkdir -p lib/stub
	g++ -Wall -g -c -I/usr/local/include/hot echo_request.cc -o lib/echo_request.o
	g++ -Wall -g -c -I/usr/local/include/hot echo_response.cc -o lib/echo_response.o
