/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 12:53:50
 * Name: gate_service.h
 * Description:
 *   This file contains definition of service interface.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE__PROXY__GATE_SERVICE_H_
#define _IR_NTNAEEM_GATE__PROXY__GATE_SERVICE_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>

#include "request.h"
#include "response.h"


namespace ir {
namespace ntnaeem {
namespace gate {
  class GateService {
  public:
    virtual void SendRequest(::ir::ntnaeem::gate::Request &request, ::naeem::hottentot::runtime::types::UInt32 &out) = 0;
    virtual void GetRequestStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::naeem::hottentot::runtime::types::UInt32 &out) = 0;
    virtual void GetResponses(::naeem::hottentot::runtime::types::Utf8String &label, ::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::Response> &out) = 0;
  };
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif