/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 12:53:50
 * Name: request.h
 * Description:
 *   This file contains definition of Request class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE__REQUEST_H_
#define _IR_NTNAEEM_GATE__REQUEST_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace ir {
namespace ntnaeem {
namespace gate {
  class Request : public ::naeem::hottentot::runtime::Serializable {
  public:
    Request() {}
    ~Request() {}
  public:
    inline ::naeem::hottentot::runtime::types::UInt32 GetId() const {
      return id_;
    }
    inline void SetId(::naeem::hottentot::runtime::types::UInt32 id) {
      id_ = id;
    }
    inline ::naeem::hottentot::runtime::types::Utf8String GetLabel() const {
      return label_;
    }
    inline void SetLabel(::naeem::hottentot::runtime::types::Utf8String label) {
      label_ = label;
    }
    inline ::naeem::hottentot::runtime::types::ByteArray GetContent() const {
      return content_;
    }
    inline void SetContent(::naeem::hottentot::runtime::types::ByteArray content) {
      content_ = content;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::UInt32 id_;
    ::naeem::hottentot::runtime::types::Utf8String label_;
    ::naeem::hottentot::runtime::types::ByteArray content_;
  };
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif