/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 03-02-2016 03:40:24
 * Name: gate_service_impl.h
 * Description:
 *   This file contains definitions of sample stub.
 ******************************************************************/
 
#ifndef _IR_NTNAEEM_GATE__GATE_SERVICE_IMPL_H_
#define _IR_NTNAEEM_GATE__GATE_SERVICE_IMPL_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include "../service/abstract_gate_service.h"


namespace ir {
namespace ntnaeem {
namespace gate {
  class GateServiceImpl : public ::ir::ntnaeem::gate::service::AbstractGateService {
  public:
    GateServiceImpl() {}
    virtual ~GateServiceImpl() {}
  public:
    virtual void OnInit();
    virtual void OnShutdown();
    virtual void EnqueueMessage(::ir::ntnaeem::gate::Message &message, ::naeem::hottentot::runtime::types::UInt64 &out);
    virtual void GetMessageStatus(::naeem::hottentot::runtime::types::UInt64 &id, ::ir::ntnaeem::gate::MessageStatus &out);
    virtual void HasMoreMessage(::naeem::hottentot::runtime::types::Utf8String &label, ::naeem::hottentot::runtime::types::Boolean &out);
    virtual void NextMessage(::naeem::hottentot::runtime::types::Utf8String &label, ::ir::ntnaeem::gate::Message &out);
  };
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif