/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 01:23:32
 * Name: transport_service_impl.cc
 * Description:
 *   This file contains empty implementation of sample stub.
 ******************************************************************/
 
#include <naeem/hottentot/runtime/configuration.h>
#include <naeem/hottentot/runtime/logger.h>
#include <naeem/hottentot/runtime/utils.h>

#include "transport_service_impl.h"

#include "../message.h"


namespace ir {
namespace ntnaeem {
namespace gate {
  void
  TransportServiceImpl::OnInit() {
    // TODO: Called when service is initializing.
  }
  void
  TransportServiceImpl::OnShutdown() {
    // TODO: Called when service is shutting down.
  }
  void
  TransportServiceImpl::Send(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::Message> &parcels, ::naeem::hottentot::runtime::types::List< ::naeem::hottentot::runtime::types::UInt32> &out) {
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "TransportServiceImpl::Send() is called." << std::endl;
    }
    // TODO
  }
  void
  TransportServiceImpl::Receive(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::Message> &out) {
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "TransportServiceImpl::Receive() is called." << std::endl;
    }
    // TODO
  }
  void
  TransportServiceImpl::GetMessageStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::naeem::hottentot::runtime::types::UInt32 &out) {
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "TransportServiceImpl::GetMessageStatus() is called." << std::endl;
    }
    // TODO
  }
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir