/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 25-01-2016 02:16:33
 * Name: accept_report.h
 * Description:
 *   This file contains definition of AcceptReport class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__ACCEPT_REPORT_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__ACCEPT_REPORT_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  class AcceptReport : public ::naeem::hottentot::runtime::Serializable {
  public:
    AcceptReport() {}
    ~AcceptReport() {}
  public:
    inline ::naeem::hottentot::runtime::types::Int16 GetStatusCode() const {
      return statusCode_;
    }
    inline void SetStatusCode(::naeem::hottentot::runtime::types::Int16 statusCode) {
      statusCode_ = statusCode;
    }
    inline ::naeem::hottentot::runtime::types::UInt64 GetMasterMId() const {
      return masterMId_;
    }
    inline void SetMasterMId(::naeem::hottentot::runtime::types::UInt64 masterMId) {
      masterMId_ = masterMId;
    }
    inline ::naeem::hottentot::runtime::types::UInt64 GetSlaveMId() const {
      return slaveMId_;
    }
    inline void SetSlaveMId(::naeem::hottentot::runtime::types::UInt64 slaveMId) {
      slaveMId_ = slaveMId;
    }
    inline ::naeem::hottentot::runtime::types::Utf8String GetErrorMessage() const {
      return errorMessage_;
    }
    inline void SetErrorMessage(::naeem::hottentot::runtime::types::Utf8String errorMessage) {
      errorMessage_ = errorMessage;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::Int16 statusCode_;
    ::naeem::hottentot::runtime::types::UInt64 masterMId_;
    ::naeem::hottentot::runtime::types::UInt64 slaveMId_;
    ::naeem::hottentot::runtime::types::Utf8String errorMessage_;
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif