/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 30-01-2016 04:23:06
 * Name: accept_report.cc
 * Description:
 *   This file contains implementation of AcceptReport class.
 ******************************************************************/

#include <iostream>
#include <string.h>

#include "accept_report.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  unsigned char *
  AcceptReport::Serialize(uint32_t *length_ptr) {
    uint32_t totalLength = 0;
    uint32_t length0 = 0;
    unsigned char *data0 = statusCode_.Serialize(&length0);
    totalLength += length0;
    uint32_t length1 = 0;
    unsigned char *data1 = masterMId_.Serialize(&length1);
    totalLength += length1;
    uint32_t length2 = 0;
    unsigned char *data2 = slaveMId_.Serialize(&length2);
    totalLength += length2;
    uint32_t length3 = 0;
    unsigned char *data3 = errorMessage_.Serialize(&length3);
    if (length3 <= 127) {
      totalLength += 1 + length3;
    } else if (length3 <= (256 * 256 - 1)) {
      totalLength += 3 + length3;
    } else if (length3 <= (256 * 256 * 256 - 1)) {
      totalLength += 3 + length3;
    }
    unsigned char *data = new unsigned char[totalLength];
    uint32_t c = 0;
    for (uint32_t i = 0; i < length0; i++) {
      data[c++] = data0[i];
    }
    for (uint32_t i = 0; i < length1; i++) {
      data[c++] = data1[i];
    }
    for (uint32_t i = 0; i < length2; i++) {
      data[c++] = data2[i];
    }
    if (length3 <= 127) {
      data[c] = length3;
      c += 1;
    } else if (length3 <= (256 * 256 - 1)) {
      data[c] = 0x82;
      data[c + 1] = length3 / 256;
      data[c + 2] = length3 % 256;
      c += 3;
    } else if (length3 <= (256 * 256 * 256 - 1)) {
      data[c] = 0x83;
      data[c + 1] = length3 / (256 * 256);
      data[c + 2] = (length3 - data[c + 1] * (256 * 256)) / 256;
      data[c + 3] = length3 % (256 * 256);
      c += 4;
    }
    for (uint32_t i = 0; i < length3; i++) {
      data[c++] = data3[i];
    }
    if (c != totalLength) {
      std::cout << "Struct Serialization: Inconsistency in length of serialized byte array." << std::endl;
      exit(1);
    };
    if (length_ptr) {
      *length_ptr = totalLength;
    }
    return data;
  }
  void
  AcceptReport::Deserialize(unsigned char *data, uint32_t length) {
    uint32_t c = 0, elength = 0;
    statusCode_.Deserialize(data + c, 2);
    c += 2;
    masterMId_.Deserialize(data + c, 8);
    c += 8;
    slaveMId_.Deserialize(data + c, 8);
    c += 8;
    if ((data[c] & 0x80) == 0) {
      elength = data[c];
      c++;
    } else {
      uint8_t ll = data[c] & 0x0f;
      if (ll == 2) {
        elength == data[c] * 256 + data[c + 1];
        c += 2;
      } else if (ll == 3) {
        elength == data[c] * 256 * 256 + data[c + 1] * 256 + data[c + 2];
        c += 3;
      }
    }
    errorMessage_.Deserialize(data + c, elength);
    c += elength;
    if (c != length) {
      std::cout << "Struct Deserialization: Inconsistency in length of deserialized byte array." << std::endl;
      exit(1);
    };
  }
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir