/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 02:51:52
 * Name: service.h
 * Description:
 *   This file contains definition of service interface.
 ***************************************************************/

#ifndef ___PROXY__SERVICE_H_
#define ___PROXY__SERVICE_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>

#include "transport_status.h"
#include "transport_message.h"



  class Service {
  public:
    virtual void (:::: &out) = 0;
  };


#endif