/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 12:53:57
 * Name: transport_service.h
 * Description:
 *   This file contains definition of service interface.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__PROXY__TRANSPORT_SERVICE_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__PROXY__TRANSPORT_SERVICE_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>

#include "message.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  class TransportService {
  public:
    virtual void Send(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::Message> &messages, ::naeem::hottentot::runtime::types::List< ::naeem::hottentot::runtime::types::UInt32> &out) = 0;
    virtual void Receive(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::Message> &out) = 0;
    virtual void GetMessageStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::naeem::hottentot::runtime::types::UInt32 &out) = 0;
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif