/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 02:52:04
 * Name: transport_status.h
 * Description:
 *   This file contains definition of TransportStatus class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__TRANSPORT_STATUS_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__TRANSPORT_STATUS_H_

#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/serializable.h>


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  class TransportStatus : public ::naeem::hottentot::runtime::Serializable {
  public:
    TransportStatus() {}
    ~TransportStatus() {}
  public:
    inline ::naeem::hottentot::runtime::types::UInt32 GetStatusCode() const {
      return statusCode_;
    }
    inline void SetStatusCode(::naeem::hottentot::runtime::types::UInt32 statusCode) {
      statusCode_ = statusCode;
    }
  public:
    virtual unsigned char * Serialize(uint32_t * /* Pointer to length */);
    virtual void Deserialize(unsigned char * /* Data */, uint32_t /* Data length */);
  private:
    ::naeem::hottentot::runtime::types::UInt32 statusCode_;
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif