/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 23-01-2016 11:53:09
 * Name: transport_service.h
 * Description:
 *   This file contains definition of service interface.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__PROXY__TRANSPORT_SERVICE_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__PROXY__TRANSPORT_SERVICE_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>

#include "transport_status.h"
#include "transport_message.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  class TransportService {
  public:
    virtual void Send(::ir::ntnaeem::gate::transport::TransportMessage &message, ::naeem::hottentot::runtime::types::UInt32 &out) = 0;
    virtual void AnyMessagesLeft(::naeem::hottentot::runtime::types::UInt32 &slaveId, ::naeem::hottentot::runtime::types::Boolean &out) = 0;
    virtual void Receive(::naeem::hottentot::runtime::types::UInt32 &slaveId, ::ir::ntnaeem::gate::transport::TransportMessage &out) = 0;
    virtual void GetStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::ir::ntnaeem::gate::transport::TransportStatus &out) = 0;
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif