all:
	g++ -c -std=c++11 -I/usr/local/include/hot ../common/queue.cc
	g++ -c -std=c++11 -I/usr/local/include/hot ../common/runtime.cc
	g++ -c -std=c++11 -I/usr/local/include/hot ../common/gate_service_impl.cc