/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 06-02-2016 12:36:46
 * Name: gate_service.h
 * Description:
 *   This file contains definition of an abstract service class.
 ******************************************************************/

#ifndef _IR_NTNAEEM_GATE__SERVICE__ABSTRACT_GATE_SERVICE_H_
#define _IR_NTNAEEM_GATE__SERVICE__ABSTRACT_GATE_SERVICE_H_

#ifdef _MSC_VER
typedef __int8 int8_t;
typedef unsigned __int8 uint8_t;
typedef __int16 int16_t;
typedef unsigned __int16 uint16_t;
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
#else
#include <stdint.h>
#endif

#include <string>

#include <naeem/hottentot/runtime/service/service.h>

#include "../message_status.h"
#include "../message.h"

#include "gate_service.h"
#include "gate_service_request_handler.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace service {
  class AbstractGateService : public GateService, public ::naeem::hottentot::runtime::service::Service {
  public:
    AbstractGateService() {}
    virtual ~AbstractGateService() {}
  public:
    inline virtual uint32_t GetServiceId() const {
      return 58024360;
    }
  protected:
    inline virtual ::naeem::hottentot::runtime::service::RequestHandler* MakeRequestHandler() {
      return new GateServiceRequestHandler(this);
    }
  };
} // END OF NAMESPACE service
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif