/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 12:53:50
 * Name: gate_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <naeem/hottentot/runtime/request.h>
#include <naeem/hottentot/runtime/response.h>

#include "gate_service_request_handler.h"
#include "abstract_gate_service.h"
#include "../gate_service.h"
#include "../request.h"
#include "../response.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace service {
  void 
  GateServiceRequestHandler::HandleRequest(::naeem::hottentot::runtime::Request &request, ::naeem::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 1018765256) {
      ::ir::ntnaeem::gate::service::AbstractGateService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::gate::service::AbstractGateService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::ir::ntnaeem::gate::Request request;
      request.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::UInt32 result;
      serviceObject->SendRequest(request, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 609212704) {
      ::ir::ntnaeem::gate::service::AbstractGateService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::gate::service::AbstractGateService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::UInt32 id;
      id.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::UInt32 result;
      serviceObject->GetRequestStatus(id, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 504981346) {
      ::ir::ntnaeem::gate::service::AbstractGateService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::gate::service::AbstractGateService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::Utf8String label;
      label.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::Response> result;
      serviceObject->GetResponses(label, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir