/****************************************************************************
 * Generated by Hottentot CC Generator
 * Date: 26-01-2016 12:58:11
 * Name: gate_service_request_handler.cc
 * Description:
 *   This file contains implementation of service's request handler class.
 ****************************************************************************/
 
#include <string.h>

#include <naeem/hottentot/runtime/request.h>
#include <naeem/hottentot/runtime/response.h>

#include "gate_service_request_handler.h"
#include "abstract_gate_service.h"
#include "../gate_service.h"
#include "../message_status.h"
#include "../message.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace service {
  void 
  GateServiceRequestHandler::HandleRequest(::naeem::hottentot::runtime::Request &request, ::naeem::hottentot::runtime::Response &response) {
    if (request.GetMethodId() == 731582484) {
      ::ir::ntnaeem::gate::service::AbstractGateService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::gate::service::AbstractGateService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::ir::ntnaeem::gate::Message message;
      message.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::UInt64 result;
      serviceObject->EnqueueMessage(message, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 1596708152) {
      ::ir::ntnaeem::gate::service::AbstractGateService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::gate::service::AbstractGateService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::UInt64 id;
      id.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::ir::ntnaeem::gate::MessageStatus result;
      serviceObject->GetMessageStatus(id, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 284715353) {
      ::ir::ntnaeem::gate::service::AbstractGateService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::gate::service::AbstractGateService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::Utf8String label;
      label.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      /*
       * Calling service method
       */
      ::naeem::hottentot::runtime::types::Boolean result;
      serviceObject->HasMoreMessage(label, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    if (request.GetMethodId() == 1392692202) {
      ::ir::ntnaeem::gate::service::AbstractGateService *serviceObject = 
        dynamic_cast< ::ir::ntnaeem::gate::service::AbstractGateService*>(service_);
      /*
       * Deserialization and making input variables
       */
      ::naeem::hottentot::runtime::types::Utf8String label;
      label.Deserialize(request.GetArgumentData(0), request.GetArgumentLength(0));
      ::naeem::hottentot::runtime::types::Boolean messageRetrieved;
      messageRetrieved.Deserialize(request.GetArgumentData(1), request.GetArgumentLength(1));
      /*
       * Calling service method
       */
      ::ir::ntnaeem::gate::Message result;
      serviceObject->NextMessage(label, messageRetrieved, result);
      /*
       * Serializiation of returned object
       */
      uint32_t serializedDataLength = 0;
      unsigned char *serializedData = result.Serialize(&serializedDataLength);

      response.SetStatusCode(0);
      response.SetData(serializedData);
      response.SetDataLength(serializedDataLength);
      return;
    }
    char errorMessage[] = "Method not found.";
    response.SetStatusCode(1);
    response.SetData((unsigned char*)errorMessage);
    response.SetDataLength(strlen(errorMessage));
  }
} // END OF NAMESPACE service
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir