/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 02:51:52
 * Name: service_impl.cc
 * Description:
 *   This file contains empty implementation of sample stub.
 ******************************************************************/
 
#include <naeem/hottentot/runtime/configuration.h>
#include <naeem/hottentot/runtime/logger.h>
#include <naeem/hottentot/runtime/utils.h>

#include "service_impl.h"

#include "../transport_status.h"
#include "../transport_message.h"



  void
  ServiceImpl::OnInit() {
    // TODO: Called when service is initializing.
  }
  void
  ServiceImpl::OnShutdown() {
    // TODO: Called when service is shutting down.
  }
  void
  ServiceImpl::(:::: &out) {
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "ServiceImpl::() is called." << std::endl;
    }
    // TODO
  }
