/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 02:52:04
 * Name: transport_service_impl.cc
 * Description:
 *   This file contains empty implementation of sample stub.
 ******************************************************************/
 
#include <naeem/hottentot/runtime/configuration.h>
#include <naeem/hottentot/runtime/logger.h>
#include <naeem/hottentot/runtime/utils.h>

#include "transport_service_impl.h"

#include "../transport_status.h"
#include "../transport_message.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  void
  TransportServiceImpl::OnInit() {
    // TODO: Called when service is initializing.
  }
  void
  TransportServiceImpl::OnShutdown() {
    // TODO: Called when service is shutting down.
  }
  void
  TransportServiceImpl::Send(::ir::ntnaeem::gate::transport::TransportMessage &message, ::naeem::hottentot::runtime::types::UInt32 &out) {
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "TransportServiceImpl::Send() is called." << std::endl;
    }
    // TODO
  }
  void
  TransportServiceImpl::Receive(::ir::ntnaeem::gate::transport::TransportMessage &out) {
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "TransportServiceImpl::Receive() is called." << std::endl;
    }
    // TODO
  }
  void
  TransportServiceImpl::GetStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::ir::ntnaeem::gate::transport::TransportStatus &out) {
    if (::naeem::hottentot::runtime::Configuration::Verbose()) {
      ::naeem::hottentot::runtime::Logger::GetOut() << "TransportServiceImpl::GetStatus() is called." << std::endl;
    }
    // TODO
  }
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir