/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 12:53:57
 * Name: transport_service_impl.h
 * Description:
 *   This file contains definitions of sample stub.
 ******************************************************************/
 
#ifndef _IR_NTNAEEM_GATE_TRANSPORT__TRANSPORT_SERVICE_IMPL_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__TRANSPORT_SERVICE_IMPL_H_

#include <stdint.h>
#include <string>

#include "../service/abstract_transport_service.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  class TransportServiceImpl : public ::ir::ntnaeem::gate::transport::service::AbstractTransportService {
  public:
    TransportServiceImpl() {}
    virtual ~TransportServiceImpl() {}
  public:
    virtual void OnInit();
    virtual void OnShutdown();
    virtual void Send(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::Message> &messages, ::naeem::hottentot::runtime::types::List< ::naeem::hottentot::runtime::types::UInt32> &out);
    virtual void Receive(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::Message> &out);
    virtual void GetMessageStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::naeem::hottentot::runtime::types::UInt32 &out);
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif