/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 26-01-2016 12:58:21
 * Name: transport_service_impl.h
 * Description:
 *   This file contains definitions of sample stub.
 ******************************************************************/
 
#ifndef _IR_NTNAEEM_GATE_TRANSPORT__TRANSPORT_SERVICE_IMPL_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__TRANSPORT_SERVICE_IMPL_H_

#include <stdint.h>
#include <string>

#include "../service/abstract_transport_service.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
  class TransportServiceImpl : public ::ir::ntnaeem::gate::transport::service::AbstractTransportService {
  public:
    TransportServiceImpl() {}
    virtual ~TransportServiceImpl() {}
  public:
    virtual void OnInit();
    virtual void OnShutdown();
    virtual void AcceptSlaveMassages(::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::TransportMessage> &messages, ::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::AcceptReport> &out);
    virtual void RetrieveSlaveMessages(::naeem::hottentot::runtime::types::UInt32 &slaveId, ::naeem::hottentot::runtime::types::List< ::ir::ntnaeem::gate::transport::TransportMessage> &out);
    virtual void Ack(::naeem::hottentot::runtime::types::List< ::naeem::hottentot::runtime::types::UInt64> &masterMIds);
    virtual void GetStatus(::naeem::hottentot::runtime::types::UInt64 &masterMId, ::ir::ntnaeem::gate::transport::TransportMessageStatus &out);
  };
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif