/******************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 02:51:52
 * Name: service_proxy_builder.h
 * Description:
 *   This file contains definition of the proxy builder class.
 ******************************************************************/

#ifndef ___PROXY__SERVICE_PROXY_BUILDER_H_
#define ___PROXY__SERVICE_PROXY_BUILDER_H_

#include <stdint.h>
#include <string>



class Service;
namespace proxy {
  class ServiceProxyBuilder {
  public:
    static Service* Create(std::string /* host */, uint32_t /* port */);
    static void Destroy(Service *);
  };
} // END OF NAMESPACE proxy


#endif