/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 22-01-2016 02:51:52
 * Name: service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef ___PROXY__SERVICE_PROXY_H_
#define ___PROXY__SERVICE_PROXY_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "../service.h"



class TransportStatus;
class TransportMessage;
namespace proxy {
  class ServiceProxy : public ::::Service, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    ServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~ServiceProxy() {}
  public:
    virtual void (:::: &);
  };
} // END OF NAMESPACE proxy


#endif