/***************************************************************
 * Generated by Hottentot CC Generator
 * Date: 23-01-2016 11:53:09
 * Name: transport_service_proxy.h
 * Description:
 *   This file contains definition of the proxy class.
 ***************************************************************/

#ifndef _IR_NTNAEEM_GATE_TRANSPORT__PROXY__TRANSPORT_SERVICE_PROXY_H_
#define _IR_NTNAEEM_GATE_TRANSPORT__PROXY__TRANSPORT_SERVICE_PROXY_H_

#include <stdint.h>
#include <string>

#include <naeem/hottentot/runtime/types/primitives.h>
#include <naeem/hottentot/runtime/proxy/proxy.h>

#include "../transport_service.h"


namespace ir {
namespace ntnaeem {
namespace gate {
namespace transport {
class TransportStatus;
class TransportMessage;
namespace proxy {
  class TransportServiceProxy : public ::ir::ntnaeem::gate::transport::TransportService, 
    public ::naeem::hottentot::runtime::proxy::Proxy {
  public:
    TransportServiceProxy(std::string host, uint32_t port) 
      : ::naeem::hottentot::runtime::proxy::Proxy(host, port) {}
    virtual ~TransportServiceProxy() {}
  public:
    virtual void Send(::ir::ntnaeem::gate::transport::TransportMessage &message, ::naeem::hottentot::runtime::types::UInt32 &);
    virtual void AnyMessagesLeft(::naeem::hottentot::runtime::types::UInt32 &slaveId, ::naeem::hottentot::runtime::types::Boolean &);
    virtual void Receive(::naeem::hottentot::runtime::types::UInt32 &slaveId, ::ir::ntnaeem::gate::transport::TransportMessage &);
    virtual void GetStatus(::naeem::hottentot::runtime::types::UInt32 &id, ::ir::ntnaeem::gate::transport::TransportStatus &);
  };
} // END OF NAMESPACE proxy
} // END OF NAMESPACE transport
} // END OF NAMESPACE gate
} // END OF NAMESPACE ntnaeem
} // END OF NAMESPACE ir

#endif